### ISSUE TITLE
Makefile:200: recipe for target 'px4_sitl' failed

### ISSUE THREAD

**Issue by malfarizit** [mzahana/mavros_apriltag_tracking#4]
hai @mzahana 
i try run : DONT_RUN=1 make px4_sitl gazebo

and got error:

-- Configuring incomplete, errors occurred!
See also "/home/al/Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeOutput.log".
See also "/home/al/Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeError.log".
[360/700] Linking CXX static library src/lib/pid/libpid.a
FAILED: cd /home/al/Firmware/build/px4_sitl_default/build_gazebo && /usr/bin/cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DSEND_VISION_ESTIMATION_DATA=ON -GNinja /home/al/Firmware/Tools/sitl_gazebo && /usr/bin/cmake -E touch /home/al/Firmware/build/px4_sitl_default/external/Stamp/sitl_gazebo/sitl_gazebo-configure
[360/700] Linking CXX static library src/lib/drivers/accelerometer/libdrivers_accelerometer.a
ninja: build stopped: subcommand failed.
Makefile:200: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1

here : 
cmake error log : [https://drive.google.com/file/d/1q4bggwaUaLwn0j31cX0cW3p57SRyCaMF/view?usp=sharing](url)
cmaker output log : [https://drive.google.com/file/d/1mF1s9U1W3ucL7T6QH98eOpd1NLyzeMZZ/view?usp=sharing](url)

how to fix this?

thanks.

**Comment by malfarizit** [comment]
OS : kubuntu 16.04
ROS distro : Kinetic
Gazebo 7

**Comment by mzahana** [comment]
@malfarizit it's a PX4 related error. Better to ask this on PX4 repo.

Which instructions you followed to build this package ?

**Comment by mzahana** [comment]
@malfarizit it's a PX4 related error. Better to ask this on PX4 repo.

Which instructions you followed to build this package ?

**Comment by malfarizit** [comment]
> @malfarizit it's a PX4 related error. Better to ask this on PX4 repo.
> 
> Which instructions you followed to build this package ?

I'm following setup.sh from your repo sir.

**Comment by malfarizit** [comment]
solved using `sudo apt-get update` after downloading px4 firmware.

If you already run `DONT_RUN=1 make px4_sitl gazebo` and failed, make sure youre running `make distclean`.

`make distclean`
`sudo apt-get update`
`reboot`

and run make again.

`DONT_RUN=1 make px4_sitl gazebo`

good luck, thanks to @mzahana Jazakallahu Khairan.

**Comment by mzahana** [comment]
Thanks for the update. There should be no need for `reboot` though, but thanks anyway.

**Comment by mzahana** [comment]
Closing since issue is solved.
